extends RefCounted
## 根据各模块 [code]editor/module_editor.gd[/code] 的 [method facade_methods] 生成 [member GDFrameConfig.EXT_FACADE_MODULES_PATH]（Dock [b]扩展管理 → 生成扩展 API[/b]）。

const _MODULE_SCAN: Script = preload("res://addons/gdframe/runtime/ext/module_scan.gd")
const _MODULE_EDITOR_SCAN: Script = preload("res://addons/gdframe/editor/module_editor_scan.gd")


## 扫描结果写入 [member GDFrameConfig.EXT_FACADE_MODULES_PATH]。返回 [code]ok[/code]、[code]changed[/code]、[code]message[/code]、[code]content[/code]。
static func generate_from_modules(modules: Array[Script]) -> Dictionary:
	var content: String = _build_source(modules)
	var module_count: int = modules.size()
	var method_count: int = _count_facade_methods(modules)
	if not _is_valid_output(content):
		return {
			"ok": false,
			"changed": false,
			"message": "生成内容无效。",
			"content": "",
		}
	if not _should_write(content):
		var msg: String = (
			"扩展 API 已是最新（%d 个模块，%d 个 facade 方法）。"
			% [module_count, method_count]
		)
		if method_count == 0:
			msg = "扩展 API 已是最新（%d 个模块；无 facade_methods，已生成空 stub）。" % module_count
		return {
			"ok": true,
			"changed": false,
			"message": msg,
			"content": content,
		}
	var write_msg: String = "已生成 %s（%d 个模块，%d 个 facade 方法）。" % [
		GDFrameConfig.EXT_FACADE_MODULES_PATH,
		module_count,
		method_count,
	]
	if method_count == 0:
		write_msg = "已生成空扩展 API stub（%d 个模块无 facade_methods）。" % module_count
	return {
		"ok": true,
		"changed": true,
		"message": write_msg,
		"content": content,
	}


static func generate_all() -> Dictionary:
	return generate_from_modules(_MODULE_SCAN.load_modules())


static func _is_valid_output(content: String) -> bool:
	return content.contains("extends \"")


static func _count_facade_methods(modules: Array[Script]) -> int:
	var count: int = 0
	for mod: Script in modules:
		var methods: Variant = _MODULE_EDITOR_SCAN.call_editor_method(mod, &"facade_methods")
		if methods == null:
			continue
		if methods is Array:
			count += (methods as Array).size()
	return count


static func _should_write(content: String) -> bool:
	var abs_path: String = ProjectSettings.globalize_path(GDFrameConfig.EXT_FACADE_MODULES_PATH)
	if not FileAccess.file_exists(abs_path):
		return true
	var existing: String = FileAccess.get_file_as_string(abs_path)
	return existing != content


static func _build_source(modules: Array[Script]) -> String:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Auto-generated by GDFrame — do not edit manually.")
	lines.append("extends \"%s\"" % GDFrameConfig.SIGNALS_SCRIPT_PATH)
	lines.append("")
	var has_methods: bool = false
	for mod: Script in modules:
		var service_key: StringName = _service_key_from_module(mod)
		var methods: Variant = _MODULE_EDITOR_SCAN.call_editor_method(mod, &"facade_methods")
		if methods == null:
			continue
		if methods is Array:
			for entry: Variant in methods:
				if entry is Dictionary:
					has_methods = true
					lines.append(_method_block(entry as Dictionary, service_key))
	if not has_methods:
		lines.append("# 当前无 facade_methods；安装带 facade 的模块后重新生成。")
	return "\n".join(lines) + "\n"


static func _service_key_from_module(mod: Script) -> StringName:
	return StringName(mod.resource_path.get_base_dir().get_file())


static func _delegate_call_expr(delegate: StringName, call_args: String) -> String:
	if call_args.is_empty():
		return 'svc.call(&"%s")' % delegate
	return 'svc.call(&"%s", %s)' % [delegate, call_args]


static func _method_block(entry: Dictionary, service_key: StringName) -> String:
	var sig: String = str(entry.get("signature", ""))
	var delegate: StringName = entry.get("delegate", entry.get("name", &""))
	var call_args: String = str(entry.get("call_args", ""))
	var sanitized: Dictionary = _sanitize_node_shadow_params(sig, call_args)
	sig = str(sanitized.get("signature", sig))
	call_args = str(sanitized.get("call_args", call_args))
	var wrap: String = str(entry.get("return_wrap", ""))
	if wrap.is_empty():
		wrap = _infer_return_wrap(sig)
	var await_service: StringName = entry.get("await_service", &"")
	var delegate_call: String = _delegate_call_expr(delegate, call_args)
	var sk: StringName = service_key
	if entry.has("service_key"):
		sk = StringName(str(entry.get("service_key")))
	var sk_str: String = String(sk)
	var service_key_str: String = String(await_service if await_service != &"" else sk)
	var lines: PackedStringArray = PackedStringArray()
	lines.append("%s:" % sig)
	lines.append("\tvar svc: Variant = GDFrame.service_get(&\"%s\")" % service_key_str)
	if await_service != &"":
		var await_call: String = "await svc.call(&\"%s\"%s)" % [
			delegate,
			"" if call_args.is_empty() else ", %s" % call_args,
		]
		if wrap == "StringName":
			lines.append("\treturn %s as StringName" % await_call)
		elif wrap.is_empty():
			lines.append("\t%s" % await_call)
		else:
			lines.append("\treturn %s" % _wrap_await_expr(wrap, await_call))
	elif wrap.is_empty():
		lines.append("\t%s" % delegate_call)
	else:
		var inner: String = delegate_call
		match wrap:
			"bool":
				lines.append("\treturn bool(%s)" % inner)
			"AudioStream":
				lines.append("\treturn %s as AudioStream" % inner)
			"Error":
				lines.append("\treturn %s as Error" % inner)
			"StringName":
				lines.append("\treturn %s as StringName" % inner)
			"float":
				lines.append("\treturn float(%s)" % inner)
			"String":
				lines.append("\treturn String(%s)" % inner)
			_:
				lines.append("\treturn %s" % inner)
	lines.append("")
	return "\n".join(lines)


static func _infer_return_wrap(signature: String) -> String:
	if signature.contains("-> void"):
		return ""
	if signature.contains("-> StringName"):
		return "StringName"
	if signature.contains("-> bool"):
		return "bool"
	if signature.contains("-> float"):
		return "float"
	if signature.contains("-> String"):
		return "String"
	if signature.contains("-> AudioStream"):
		return "AudioStream"
	if signature.contains("-> Error"):
		return "Error"
	return ""


static func _wrap_await_expr(wrap: String, await_call: String) -> String:
	match wrap:
		"bool":
			return "bool(%s)" % await_call
		"float":
			return "float(%s)" % await_call
		"String":
			return "String(%s)" % await_call
		"AudioStream":
			return "%s as AudioStream" % await_call
		"Error":
			return "%s as Error" % await_call
		_:
			return await_call


## 避免 facade 参数名遮蔽 [Node] 基类属性（如 [member Node.name]）。
static func _sanitize_node_shadow_params(signature: String, call_args: String) -> Dictionary:
	var out_sig: String = signature
	var out_args: String = call_args
	for old_name: String in _node_shadow_param_renames():
		if not _signature_has_param(out_sig, old_name):
			continue
		var new_name: String = str(_node_shadow_param_renames()[old_name])
		out_sig = _rename_param_in_signature(out_sig, old_name, new_name)
		out_args = _rename_call_arg(out_args, old_name, new_name)
	return {"signature": out_sig, "call_args": out_args}


static func _node_shadow_param_renames() -> Dictionary:
	return {
		"name": "p_name",
		"owner": "p_owner",
		"process_mode": "p_process_mode",
	}


static func _signature_has_param(signature: String, param_name: String) -> bool:
	var open_idx: int = signature.find("(")
	var close_idx: int = signature.rfind(")")
	if open_idx < 0 or close_idx <= open_idx:
		return false
	var params: String = signature.substr(open_idx + 1, close_idx - open_idx - 1).strip_edges()
	if params.is_empty():
		return false
	for part: String in params.split(","):
		var trimmed: String = part.strip_edges()
		if trimmed.is_empty():
			continue
		var param_head: String = _param_head_from_signature_part(trimmed)
		if param_head == param_name:
			return true
	return false


static func _param_head_from_signature_part(part: String) -> String:
	var typed: PackedStringArray = part.split(":", false, 1)
	var head: String = typed[0].strip_edges() if typed.size() > 0 else part.strip_edges()
	var ident: PackedStringArray = head.split(" ", false)
	return ident[0] if ident.size() > 0 else head


static func _rename_param_in_signature(signature: String, old_name: String, new_name: String) -> String:
	var open_idx: int = signature.find("(")
	var close_idx: int = signature.rfind(")")
	if open_idx < 0 or close_idx <= open_idx:
		return signature
	var head: String = signature.substr(0, open_idx + 1)
	var tail: String = signature.substr(close_idx)
	var params: String = signature.substr(open_idx + 1, close_idx - open_idx - 1)
	var renamed: PackedStringArray = PackedStringArray()
	for part: String in params.split(","):
		var trimmed: String = part.strip_edges()
		if trimmed.is_empty():
			continue
		var param_head: String = _param_head_from_signature_part(trimmed)
		if param_head == old_name:
			trimmed = new_name + trimmed.substr(old_name.length())
		renamed.append(trimmed)
	return "%s%s%s" % [head, ", ".join(renamed), tail]


static func _rename_call_arg(call_args: String, old_name: String, new_name: String) -> String:
	if call_args.is_empty():
		return call_args
	var renamed: PackedStringArray = PackedStringArray()
	for part: String in call_args.split(","):
		var trimmed: String = part.strip_edges()
		renamed.append(new_name if trimmed == old_name else trimmed)
	return ", ".join(renamed)
