extends RefCounted
## 扫描各模块 [code]editor/module_editor.gd[/code] 的 [method profile_fields] 生成 [member GDFrameConfig.PROFILE_SETTINGS_SCRIPT_PATH] 与
## [member GDFrameConfig.PROFILE_SETTINGS_DEFAULTS_PATH]（Dock [b]扩展管理 → 生成扩展 API[/b] 与插件启用时同步）。

const _MODULE_SCAN: Script = preload("res://addons/gdframe/runtime/ext/module_scan.gd")
const _MODULE_EDITOR_SCAN: Script = preload("res://addons/gdframe/editor/module_editor_scan.gd")

const MARKER_GEN_BEGIN: String = "## GDFrame generated profile fields — do not edit"
const MARKER_GEN_END: String = "## GDFrame generated profile fields end"
const MARKER_CUSTOM_BEGIN: String = "# --- 业务自定义 profile 字段（可编辑）---"


static func skeleton_template() -> String:
	return (
		"extends GDFrameSettingsData\n"
		+ "class_name GDFrameProfileSettingsData\n"
		+ "## 工程 profile 设置：核心字段见 [code]GDFrameSettingsData[/code]；业务 [code]@export[/code] 写在上方自定义段；扩展 [code]@export[/code] 由 Dock [b]扩展管理 → 生成扩展 API[/b] 写入下方自动生成段。\n\n"
		+ MARKER_CUSTOM_BEGIN
		+ "\n"
		+ _default_custom_body()
		+ "\n\n"
		+ MARKER_GEN_BEGIN
		+ "\n\n"
		+ MARKER_GEN_END
		+ "\n"
	)


static func generate_all() -> Dictionary:
	return generate_from_modules(_MODULE_SCAN.load_modules())


static func generate_from_modules(modules: Array[Script]) -> Dictionary:
	var fields: Array[Dictionary] = _collect_profile_fields(modules)
	var data_content: String = _build_profile_settings_data(fields, _read_custom_section())
	var defaults_content: String = _build_defaults_script(fields)
	if data_content.is_empty() or defaults_content.is_empty():
		return {
			"ok": false,
			"changed_data": false,
			"changed_defaults": false,
			"message": "profile 生成内容无效。",
			"data_content": "",
			"defaults_content": "",
		}
	var changed_data: bool = _should_write(GDFrameConfig.PROFILE_SETTINGS_SCRIPT_PATH, data_content)
	var changed_defaults: bool = _should_write(
		GDFrameConfig.PROFILE_SETTINGS_DEFAULTS_PATH,
		defaults_content,
	)
	var field_count: int = fields.size()
	var msg: String
	if changed_data or changed_defaults:
		msg = (
			"已同步 profile 字段（%d 个 @export）至 profile_settings_data.gd。"
			% field_count
		)
		if field_count == 0:
			msg = "已同步 profile 字段（当前无 profile_fields，自动生成段为空）。"
	else:
		msg = "profile 字段已是最新（%d 个 @export）。" % field_count
	return {
		"ok": true,
		"changed_data": changed_data,
		"changed_defaults": changed_defaults,
		"message": msg,
		"data_content": data_content,
		"defaults_content": defaults_content,
	}


static func _collect_profile_fields(modules: Array[Script]) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	var seen: Dictionary = {}
	for mod: Script in modules:
		var raw: Variant = _MODULE_EDITOR_SCAN.call_editor_method(mod, &"profile_fields")
		if raw == null:
			continue
		if not raw is Array:
			continue
		for entry: Variant in raw:
			if not entry is Dictionary:
				continue
			var field: Dictionary = (entry as Dictionary).duplicate(true)
			var name: String = String(field.get("name", "")).strip_edges()
			if name.is_empty():
				continue
			if seen.has(name):
				push_warning(
					"GDFrame profile: 重复字段 %s（跳过 %s）"
					% [name, mod.resource_path]
				)
				continue
			seen[name] = true
			field["name"] = name
			out.append(field)
	return out


static func _build_profile_settings_data(fields: Array[Dictionary], custom_section: String) -> String:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("extends GDFrameSettingsData")
	lines.append("class_name GDFrameProfileSettingsData")
	lines.append(
		"## 工程 profile 设置：核心字段见 [code]GDFrameSettingsData[/code]；业务 [code]@export[/code] 写在上方自定义段；扩展 [code]@export[/code] 由 Dock [b]扩展管理 → 生成扩展 API[/b] 写入下方自动生成段。"
	)
	lines.append("")
	lines.append(MARKER_CUSTOM_BEGIN)
	if custom_section.is_empty():
		lines.append(_default_custom_body())
	else:
		lines.append(custom_section)
	lines.append("")
	lines.append(MARKER_GEN_BEGIN)
	for field: Dictionary in fields:
		var comment: String = String(field.get("comment", "")).strip_edges()
		if not comment.is_empty():
			lines.append("## %s" % comment)
		lines.append(_export_line(field))
	if fields.is_empty():
		lines.append("# （当前已安装模块无 profile_fields）")
	lines.append(MARKER_GEN_END)
	return "\n".join(lines) + "\n"


static func _default_custom_body() -> String:
	return "# @export var example_setting: bool = true"


static func _build_defaults_script(fields: Array[Dictionary]) -> String:
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Auto-generated by GDFrame — do not edit manually.")
	lines.append("extends RefCounted")
	lines.append("class_name GDFrameProfileSettingsDefaults")
	if fields.is_empty():
		lines.append("")
		lines.append("# （当前已安装模块无 profile_fields）")
	else:
		lines.append("")
		lines.append("static func apply(settings: GDFrameSettingsData) -> void:")
		for field: Dictionary in fields:
			lines.append("\t%s" % _default_apply_line(field))
	return "\n".join(lines) + "\n"


static func _export_line(field: Dictionary) -> String:
	var name: String = String(field.get("name", ""))
	var type_name: String = String(field.get("type", "Variant"))
	var default_literal: String = _format_default_literal(field.get("default"), type_name)
	return "@export var %s: %s = %s" % [name, type_name, default_literal]


static func _default_apply_line(field: Dictionary) -> String:
	var name: String = String(field.get("name", ""))
	var type_name: String = String(field.get("type", "Variant"))
	var default_literal: String = _format_default_literal(field.get("default"), type_name)
	if type_name == "Dictionary":
		return 'if not settings.get("%s") is Dictionary:\n\t\tsettings.set("%s", %s)' % [
			name,
			name,
			default_literal,
		]
	if type_name == "Array":
		return 'if not settings.get("%s") is Array:\n\t\tsettings.set("%s", %s)' % [
			name,
			name,
			default_literal,
		]
	return 'if settings.get("%s") == null:\n\t\tsettings.set("%s", %s)' % [
		name,
		name,
		default_literal,
	]


static func _format_default_literal(default_value: Variant, type_name: String) -> String:
	if default_value == null:
		match type_name:
			"Dictionary":
				return "{}"
			"Array":
				return "[]"
			"String":
				return '""'
			"bool":
				return "false"
			"int":
				return "0"
			"float":
				return "0.0"
			_:
				return "null"
	if default_value is bool:
		return "true" if default_value else "false"
	if default_value is int:
		return str(default_value)
	if default_value is float:
		return str(default_value)
	if default_value is String:
		return '"%s"' % (default_value as String).c_escape()
	if default_value is Dictionary:
		return "{}"
	if default_value is Array:
		return "[]"
	return str(default_value)


static func _read_custom_section() -> String:
	var existing: String = _read_existing_script()
	if existing.is_empty():
		return ""
	var custom_idx: int = existing.find(MARKER_CUSTOM_BEGIN)
	if custom_idx < 0:
		return ""
	var after_custom: String = existing.substr(custom_idx + MARKER_CUSTOM_BEGIN.length())
	var gen_after: int = after_custom.find(MARKER_GEN_BEGIN)
	var slice: String = after_custom
	if gen_after >= 0:
		slice = after_custom.substr(0, gen_after)
	return slice.strip_edges()


static func _read_existing_script() -> String:
	var abs_path: String = ProjectSettings.globalize_path(GDFrameConfig.PROFILE_SETTINGS_SCRIPT_PATH)
	if not FileAccess.file_exists(abs_path):
		return ""
	return FileAccess.get_file_as_string(abs_path)


static func _should_write(res_path: String, content: String) -> bool:
	var abs_path: String = ProjectSettings.globalize_path(res_path)
	if not FileAccess.file_exists(abs_path):
		return true
	return FileAccess.get_file_as_string(abs_path) != content
