extends RefCounted
## 汇总扩展 [code]editor/module_editor.gd[/code] 的 [method generate_audio_channels]，
## 写入 [member GDFrameConfig.AUDIO_CHANNELS_PATH]。
## 无提供方时写回空壳，保留 [code]class_name GDFrameAudioChannels[/code]。

const _MODULE_SCAN: Script = preload("res://addons/gdframe/runtime/ext/module_scan.gd")
const _MODULE_EDITOR_SCAN: Script = preload("res://addons/gdframe/editor/module_editor_scan.gd")


static func empty_source() -> String:
	return (
		"## Auto-generated by GDFrame - do not edit manually.\n"
		+ "extends GDFrameAudioManager\n"
		+ "class_name GDFrameAudioChannels\n"
	)


static func generate_all() -> Dictionary:
	var providers: Array[Dictionary] = []
	for mod: Script in _MODULE_SCAN.load_modules():
		var raw: Variant = _MODULE_EDITOR_SCAN.call_editor_method(mod, &"generate_audio_channels")
		if raw is Dictionary:
			providers.append(raw as Dictionary)
	if providers.size() > 1:
		return {
			"ok": false,
			"changed": false,
			"message": "多个扩展实现了 generate_audio_channels，未写入 audio_channels.gd。",
			"content": "",
		}
	if providers.is_empty():
		return _pack(
			empty_source(),
			"GDFrameAudioChannels 已是空壳。",
			"已写回 %s 空壳。" % GDFrameConfig.AUDIO_CHANNELS_PATH,
		)
	var built: Dictionary = providers[0]
	if not bool(built.get("ok", false)):
		var fail_msg: String = str(built.get("message", "audio_channels 生成失败。"))
		if not _file_exists():
			return _pack(
				empty_source(),
				fail_msg,
				"%s 已写回 %s 空壳。" % [fail_msg, GDFrameConfig.AUDIO_CHANNELS_PATH],
			)
		return {
			"ok": false,
			"changed": false,
			"message": fail_msg,
			"content": "",
		}
	var content: String = str(built.get("content", ""))
	if not content.contains("class_name GDFrameAudioChannels"):
		return {
			"ok": false,
			"changed": false,
			"message": "generate_audio_channels 内容无效。",
			"content": "",
		}
	return _pack(
		content,
		"audio_channels.gd 已是最新。",
		str(built.get("message", "已生成 audio_channels.gd。")),
	)


static func _pack(content: String, same_msg: String, wrote_msg: String) -> Dictionary:
	var changed: bool = _should_write(content)
	return {
		"ok": true,
		"changed": changed,
		"message": wrote_msg if changed else same_msg,
		"content": content,
	}


static func _file_exists() -> bool:
	return FileAccess.file_exists(ProjectSettings.globalize_path(GDFrameConfig.AUDIO_CHANNELS_PATH))


static func _should_write(content: String) -> bool:
	if not _file_exists():
		return true
	var existing: String = FileAccess.get_file_as_string(
		ProjectSettings.globalize_path(GDFrameConfig.AUDIO_CHANNELS_PATH)
	)
	return existing != content
