extends RefCounted
## 根据各模块 [code]editor/module_editor.gd[/code] 的 [method ext_service_type]
## 生成 [member GDFrameConfig.EXT_SLOTS_PATH]（Dock [b]扩展管理 → 生成扩展 API[/b]）。
## 生成体：强类型服务槽位 [code]GDFrame.example[/code] 等；业务直调服务方法，不生成方法透传层。

const _MODULE_SCAN: Script = preload("res://addons/gdframe/runtime/ext/module_scan.gd")
const _MODULE_EDITOR_SCAN: Script = preload("res://addons/gdframe/editor/module_editor_scan.gd")


## 扫描结果写入 [member GDFrameConfig.EXT_SLOTS_PATH]。返回 [code]ok[/code]、[code]changed[/code]、[code]message[/code]、[code]content[/code]。
static func generate_from_modules(modules: Array[Script]) -> Dictionary:
	var built: Dictionary = _build_source(modules)
	if not bool(built.get("ok", false)):
		return {
			"ok": false,
			"changed": false,
			"message": str(built.get("message", "生成失败。")),
			"content": "",
		}
	var content: String = str(built.get("content", ""))
	var module_count: int = modules.size()
	var slot_count: int = int(built.get("slot_count", 0))
	if not _is_valid_output(content):
		return {
			"ok": false,
			"changed": false,
			"message": "生成内容无效。",
			"content": "",
		}
	if not _should_write(content):
		var msg: String = "扩展服务槽位已是最新（%d 个模块，%d 个槽位）。" % [module_count, slot_count]
		if slot_count == 0:
			msg = "扩展服务槽位已是最新（%d 个模块；无 ext_service_type，已生成空 stub）。" % module_count
		return {
			"ok": true,
			"changed": false,
			"message": msg,
			"content": content,
		}
	var write_msg: String = "已生成 %s（%d 个模块，%d 个服务槽位）。" % [
		GDFrameConfig.EXT_SLOTS_PATH,
		module_count,
		slot_count,
	]
	if slot_count == 0:
		write_msg = "已生成空扩展服务槽位 stub（%d 个模块无 ext_service_type）。" % module_count
	return {
		"ok": true,
		"changed": true,
		"message": write_msg,
		"content": content,
	}


static func generate_all() -> Dictionary:
	return generate_from_modules(_MODULE_SCAN.load_modules())


static func _is_valid_output(content: String) -> bool:
	return content.contains("extends \"")


static func _should_write(content: String) -> bool:
	var abs_path: String = ProjectSettings.globalize_path(GDFrameConfig.EXT_SLOTS_PATH)
	if not FileAccess.file_exists(abs_path):
		return true
	var existing: String = FileAccess.get_file_as_string(abs_path)
	return existing != content


static func _build_source(modules: Array[Script]) -> Dictionary:
	var slots: Array[Dictionary] = []
	for mod: Script in modules:
		var service_key: StringName = _service_key_from_module(mod)
		var svc_type_v: Variant = _MODULE_EDITOR_SCAN.call_editor_method(mod, &"ext_service_type")
		var svc_type: String = str(svc_type_v).strip_edges() if svc_type_v != null else ""
		if svc_type.is_empty():
			continue
		slots.append({"key": String(service_key), "type": svc_type})
	slots.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		return str(a.get("key", "")) < str(b.get("key", ""))
	)
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## Auto-generated by GDFrame - do not edit manually.")
	lines.append("extends \"%s\"" % GDFrameConfig.SIGNALS_SCRIPT_PATH)
	lines.append("")
	if slots.is_empty():
		lines.append("# 当前无 ext_service_type；安装带服务类型的模块后重新生成。")
		lines.append("")
		lines.append("func _bind_ext_service(_key: StringName, _service: Variant) -> void:")
		lines.append("\tpass")
		lines.append("")
		return {
			"ok": true,
			"content": "\n".join(lines),
			"slot_count": 0,
		}
	for slot: Dictionary in slots:
		lines.append("var %s: %s" % [str(slot["key"]), str(slot["type"])])
	lines.append("")
	lines.append("func _bind_ext_service(key: StringName, service: Variant) -> void:")
	lines.append("\tmatch key:")
	for slot: Dictionary in slots:
		var key: String = str(slot["key"])
		var typ: String = str(slot["type"])
		lines.append("\t\t&\"%s\":" % key)
		lines.append("\t\t\t%s = service as %s" % [key, typ])
	lines.append("\t\t_:")
	lines.append("\t\t\tpass")
	lines.append("")
	return {
		"ok": true,
		"content": "\n".join(lines),
		"slot_count": slots.size(),
	}


static func _service_key_from_module(mod: Script) -> StringName:
	return StringName(
		GDFrameConfig.ext_normalize_module_id(mod.resource_path.get_base_dir().get_file())
	)
